<?php

namespace Database\Seeders;

use App\Enums\EventType;
use App\Enums\PaymentStatus;
use Domain\Booking\Models\Booking;
use Domain\Facility\Models\Area;
use Domain\User\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalendarImportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Imports calendar data from CSV file generated by Gemini preprocessing.
     * CSV format: date,title,start_time,end_time,notes,sheet_count
     */
    public function run(): void
    {
        $csvPath = database_path('seeders/data/calendar_import_2025_2026.csv');

        if (! file_exists($csvPath)) {
            $this->command->error("CSV file not found: {$csvPath}");
            $this->command->info('Please run the data filtering and Gemini preprocessing steps first.');
            $this->command->info('See: scripts/gemini-prompt.md for instructions');

            return;
        }

        $this->command->info('📅 Starting Calendar Import...');
        $this->command->info('Reading CSV: '.$csvPath);

        // Get the admin user (first user or create a system user)
        $adminUser = User::first();
        if (! $adminUser) {
            $this->command->error('No users found in database. Please run UserSeeder first.');

            return;
        }

        // Get available areas (ice sheets)
        $sheets = Area::where('name', 'like', 'Sheet %')->get();
        if ($sheets->isEmpty()) {
            $this->command->error('No ice sheets found. Please run AreaAndAvailabilitySeeder first.');

            return;
        }

        // Open and parse CSV
        $file = fopen($csvPath, 'r');
        $header = fgetcsv($file); // Skip header row

        // Validate CSV header
        $expectedHeaders = ['date', 'title', 'start_time', 'end_time', 'notes', 'sheet_count'];
        if ($header !== $expectedHeaders) {
            $this->command->warn('CSV header mismatch. Expected: '.implode(',', $expectedHeaders));
            $this->command->warn('Got: '.implode(',', $header));
        }

        $imported = 0;
        $skipped = 0;
        $errors = [];

        DB::beginTransaction();

        try {
            while (($row = fgetcsv($file)) !== false) {
                // Skip empty rows
                if (empty($row[0])) {
                    continue;
                }

                // Parse CSV columns
                [$date, $title, $startTime, $endTime, $notes, $sheetCount] = array_pad($row, 6, null);

                // Validate required fields
                if (empty($date) || empty($title) || empty($startTime) || empty($endTime)) {
                    $skipped++;
                    $errors[] = "Skipped row: missing required fields - Date: {$date}, Title: {$title}";

                    continue;
                }

                // Determine which areas/sheets to assign
                $areasToAssign = $this->determineAreas($sheets, $sheetCount, $title);

                // Create the booking
                try {
                    $booking = Booking::create([
                        'user_id' => $adminUser->id,
                        'title' => $title,
                        'date' => $date,
                        'start_time' => $startTime,
                        'end_time' => $endTime,
                        'event_type' => EventType::PRIVATE,
                        'payment_status' => PaymentStatus::PENDING,
                        'setup_instructions' => $notes,
                    ]);

                    // Attach areas
                    foreach ($areasToAssign as $area) {
                        $booking->areas()->attach($area->id, [
                            'custom_price' => null, // Use area's base price
                        ]);
                    }

                    $imported++;

                    if ($imported % 10 === 0) {
                        $this->command->info("Imported {$imported} bookings...");
                    }
                } catch (\Exception $e) {
                    $skipped++;
                    $errors[] = "Failed to create booking '{$title}' on {$date}: ".$e->getMessage();
                }
            }

            DB::commit();
            fclose($file);

            // Summary
            $this->command->info('');
            $this->command->info('✅ Calendar Import Complete!');
            $this->command->info("Successfully imported: {$imported} bookings");

            if ($skipped > 0) {
                $this->command->warn("Skipped: {$skipped} rows");
                if (! empty($errors)) {
                    $this->command->warn('');
                    $this->command->warn('Errors:');
                    foreach (array_slice($errors, 0, 10) as $error) {
                        $this->command->warn("  - {$error}");
                    }
                    if (count($errors) > 10) {
                        $this->command->warn('  ... and '.(count($errors) - 10).' more errors');
                    }
                }
            }
        } catch (\Exception $e) {
            DB::rollBack();
            fclose($file);
            $this->command->error('Import failed: '.$e->getMessage());
            throw $e;
        }
    }

    /**
     * Determine which areas/sheets to assign based on sheet count or title hints
     *
     * @param  \Illuminate\Database\Eloquent\Collection  $sheets
     */
    private function determineAreas($sheets, ?string $sheetCount, string $title): array
    {
        // Parse sheet count from CSV
        $count = 1; // Default to 1 sheet
        if (! empty($sheetCount) && is_numeric($sheetCount)) {
            $count = (int) $sheetCount;
        } elseif (! empty($sheetCount) && preg_match('/(\d+)/', $sheetCount, $matches)) {
            $count = (int) $matches[1];
        }

        // Clamp to available sheets
        $count = min($count, $sheets->count());
        $count = max($count, 1);

        // Return the first N sheets
        return $sheets->take($count)->all();
    }
}
