// src/data/memberships.ts

import type { Membership } from "../types";

export const memberships: Membership[] = [
  // Unlimited Memberships
  {
    id: 1,
    name: "Unlimited Curling ",
    subtitle: "Evenings & Daytime",
    description: "For those who want to curl as much as they want",
    price: 550.0,
    newMemberPrice: 455.0,
    type: "Active",
    duration: "Full Year",
    category: "Unlimited",
    curlingIoId: 9757,
    newMemberCurlingIoId: 9760,
  },
  {
    id: 5,
    name: "Half-Year Unlimited Curling",
    subtitle: "Evenings & Daytime",
    description: "For those looking to curl for half the year",
    price: 355.0,
    newMemberPrice: 300.0,
    type: "Half Year",
    duration: "Half Year",
    category: "Unlimited",
    curlingIoId: 9761,
    newMemberCurlingIoId: 9762,
  },

  // Multi-Adult Memberships
  {
    id: 2,
    name: "2 Adults Unlimited Curling",
    subtitle: "Evenings & Daytime",
    description: "For two adults living at the same address",
    price: 1010.0,
    newMemberPrice: 810.0,
    type: "Active",
    duration: "Full Year",
    category: "Unlimited",
    curlingIoId: 9758,
    newMemberCurlingIoId: 9759,
  },

  // League Memberships
  {
    id: 7,
    name: "League Play",
    subtitle: "One Evening",
    description: "For those who want to curl in a league once a week",
    price: 400.0,
    newMemberPrice: 355.0,
    type: "League",
    duration: "Full Year",
    category: "Limited",
    curlingIoId: 9763,
    newMemberCurlingIoId: 9764,
  },
  // Student Memberships
  {
    id: 8,
    name: "League Play - Student",
    subtitle: "One Evening",
    description: "Student Price for League Play",
    price: 315.0,
    newMemberPrice: 250.0,
    type: "Other",
    duration: "Full Year",
    category: "Limited",
    curlingIoId: 9766,
    newMemberCurlingIoId: 9767,
  },
  {
    id: 9,
    name: "Stick Curling League",
    subtitle: "One Day",
    description:
      "For those who want to curl in a stick curling league one day per week",
    price: 400.0,
    type: "League",
    duration: "Full Year",
    category: "Limited",
    curlingIoId: 9765,
  },
  {
    id: 14,
    name: "Green League",
    subtitle: "One Day",
    description:
      "Development League for new curlers from the Learn to Curl program",
    price: 270.0,
    type: "Additional",
    duration: null,
    category: "Limited",
    additionalFees: false,
    curlingIoId: 9756,
  },
  {
    id: 17,
    name: "Green League First Half",
    subtitle: "Oct-Dec 2025",
    description:
      "First half of the Green League development program for new curlers",
    price: 160.0,
    type: "Additional",
    duration: "Half Year",
    category: "Limited",
    additionalFees: false,
    curlingIoId: 9755,
  },
  {
    id: 18,
    name: "Learn to Curl Program",
    subtitle: "Oct 20-Dec 15",
    description:
      "Adult Learn to Curl Program - perfect for beginners wanting to try curling",
    price: 80.0,
    type: "Program",
    duration: null,
    category: "Beginner",
    additionalFees: false,
    curlingIoId: 9754,
  },

  // Additional Fees
  {
    id: 13,
    name: "Social Member",
    subtitle: "",
    description: "Enjoy the ammenities of the club without curling",
    price: 60.0,
    type: "Membership",
    duration: null,
    category: "Limited",
    additionalFees: false,
    curlingIoId: 9768,
  },

  {
    id: 15,
    name: "Locker Rental",
    subtitle: "",
    description: "",
    price: 25.0,
    type: "Additional",
    duration: null,
    category: "Locker",
    additionalFees: true,
    curlingIoId: 9769,
  },
  {
    id: 16,
    name: "Key Fob",
    subtitle: "",
    description: "",
    price: 20.0,
    type: "Additional",
    duration: null,
    category: "Key",
    additionalFees: true,
    curlingIoId: 9770,
  },
];
